### ISSUE TITLE
Flesh out repo

### ISSUE THREAD

**Issue by TheNotary** [TheNotary/helm-blackbox-exporter#1]
###### TODO

- [ ] Get working deployment template
- [ ] Get working configmap that mounts a yaml to /config/blackbox.yml
- [ ] Deploy manually via helm
- [ ] Build simple dashboard
- [ ] Add Jenkinsfile
- [ ] Enable setting scrape targets via settings in values.yaml
